cc_binary (
name = 'pshm_create',
srcs = [
    'pshm_create.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib',
    '#rt',
],
)
cc_binary (
name = 'pshm_read',
srcs = [
    'pshm_read.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib',
    '#rt',
],
)
cc_binary (
name = 'pshm_write',
srcs = [
    'pshm_write.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib',
    '#rt',
],
)
cc_binary (
name = 'pshm_unlink',
srcs = [
    'pshm_unlink.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib',
    '#rt',
],
)
