cc_binary (
name = 'mmcat',
srcs = [
    'mmcat.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
cc_binary (
name = 't_mmmap',
srcs = [
    't_mmmap.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
