cc_binary (
name = 'us_xfr_sv',
srcs = [
    'us_xfr_sv.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
cc_binary (
name = 'us_xfr_cl',
srcs = [
    'us_xfr_cl.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
cc_binary (
name = 'ud_ucase_cl',
srcs = [
    'ud_ucase_cl.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
cc_binary (
name = 'ud_ucase_sv',
srcs = [
    'ud_ucase_sv.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
