cc_library (
name = 'thread_incr',
srcs = [
	'thread_incr.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],


)
cc_library (
name = 'thread_incr_mutex',
srcs = [
	'thread_incr_mutex.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],

)
cc_library (
name = 'thread_multijoin',
srcs = [
	'thread_multijoin.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],

)
cc_library (
name = 'prod_condvar',
srcs = [
	'prod_condvar.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],

)
cc_library (
name = 'prod_no_condvar',
srcs = [
	'prod_no_condvar.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],

)
