cc_binary (
name = 'thread_incr_rwlock',
srcs = [
	'thread_incr_rwlock.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],
extra_cppflags = [                                                                                                                                                                   
    '-std=gnu99',
]
)
cc_binary (
name = 'thread_incr_spinlock',
srcs = [
	'thread_incr_spinlock.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],
extra_cppflags = [                                                                                                                                                                   
    '-std=gnu99',
]
)
cc_binary (
name = 'thread_lock_speed',
srcs = [
	'thread_lock_speed.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],
extra_cppflags = [                                                                                                                                                                   
    '-std=gnu99',
]
)
