cc_binary (
name = 'multi_descriptors',
srcs = [
	'multi_descriptors.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib'
],
)
cc_binary (
name = 't_readv',
srcs = [
	't_readv.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib'
],
)
cc_binary (
name = 't_truncate',
srcs = [
	't_truncate.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib'
],
)
cc_binary (
name = 'large_file',
srcs = [
	'large_file.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib'
],
)
cc_binary (
name = 'atomic_append',
srcs = [
	'atomic_append.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib'
],
)
cc_binary (
name = 'bad_exclusive_open',
srcs = [
	'bad_exclusive_open.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib'
],
)
cc_binary (
name = 'make_tmp_file',
srcs = [
    'make_tmp_file.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
