/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Mon Aug  7 23:42:16 2017";
extern const char kBuilderName[] = "sunguangbo";
extern const char kHostName[] = "localhost";
extern const char kCompiler[] = "GCC 4.2.1";
}}
