/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"commit 7e3d23238c7859758e4901bf38a97e9ac2d83ddf\n"
"Author: broadsun <onlyforsgb@163.com>\n"
"Date:   Wed Aug 9 00:28:29 2017 +0800\n"
"\n"
"    LinuxC begin\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Sat Oct 28 22:48:34 2017";
extern const char kBuilderName[] = "sunguangbo";
extern const char kHostName[] = "localhost";
extern const char kCompiler[] = "GCC 4.2.1";
}}
