cc_binary (
name = 'simple_thread',
srcs = [
	'simple_thread.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread'
],

)
cc_binary (
name = 'detached_attrib',
srcs = [
	'detached_attrib.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread'
],

)
