cc_binary (
name = 'idshow',
srcs = [
    'idshow.c',
],
incs = [
    '../ch03_lib',
    '../ch08_Users_and_Groups',
],
deps = [
    '//ch03_lib:lib',
    '//ch08_Users_and_Groups:ugid_functions'
],
)
