cc_binary (
name = 'thread_cancel',
srcs = [
	'thread_cancel.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],

)
cc_binary (
name = 'thread_cleanup',
srcs = [
	'thread_cleanup.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib',
    '#pthread',
],

)
