cc_binary (
name = 'anon_mmap',
srcs = [
    'anon_mmap.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib',
],
)
cc_binary (
name = 'mmcat',
srcs = [
    'mmcat.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib',
],
)
cc_binary (
name = 't_mmap',
srcs = [
    't_mmap.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib',
],
)
