cc_binary (
name = 'copy',
srcs = [
	'copy.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib'
],
)
cc_binary (
name = 'seek_io',
srcs = [
	'seek_io.c',
],
incs = [
	'../ch03_lib',
],
deps = [
	'//ch03_lib:lib'
],
)
