cc_binary (
name = 'free_and_sbrk',
srcs = [
    'free_and_sbrk.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
cc_binary (
name = 'test',
srcs = [
    'test.cpp',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
