cc_library (
name = 'curr_time',
srcs = [
    'curr_time.c',
],
)
cc_binary (
name = 'calendar_time',
srcs = [
    'calendar_time.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
cc_binary (
name = 'show_time',
srcs = [
    'show_time.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
cc_binary (
name = 't_stime',
srcs = [
    't_stime.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
cc_binary (
name = 'process_time',
srcs = [
    'process_time.c',
],
incs = [
    '../ch03_lib',
],
deps = [
    '//ch03_lib:lib'
],
)
